# Generated by Django 4.2.1 on 2023-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phoneNo', models.IntegerField()),
                ('applicant_address', models.CharField(max_length=600)),
                ('applicant_shortIntro', models.TextField(blank=True, null=True)),
                ('applicant_image', models.ImageField(blank=True, null=True, upload_to='applicant')),
                ('applicant_resume', models.FileField(blank=True, null=True, upload_to='applicant')),
            ],
        ),
    ]
